// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsAmoNNqK2gia__5GBVDt8UIFBskO2x5I',
    appId: '1:343403843881:web:f7150802b4f21115592738',
    messagingSenderId: '343403843881',
    projectId: 'chatfriend-e2388',
    authDomain: 'chatfriend-e2388.firebaseapp.com',
    storageBucket: 'chatfriend-e2388.appspot.com',
    measurementId: 'G-M0DVEGNSMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMklydkNMoAd4wib_IF35xfuFCiOd0bgk',
    appId: '1:343403843881:android:05c7eba716eca66f592738',
    messagingSenderId: '343403843881',
    projectId: 'chatfriend-e2388',
    storageBucket: 'chatfriend-e2388.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArupvFox3x3iPUeGPE8sZKC_4JWoqgTFE',
    appId: '1:343403843881:ios:754746997793bb83592738',
    messagingSenderId: '343403843881',
    projectId: 'chatfriend-e2388',
    storageBucket: 'chatfriend-e2388.appspot.com',
    iosClientId: '343403843881-eukh6c1sq9k5e08ph1jorj2t4u4fdeb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFriend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArupvFox3x3iPUeGPE8sZKC_4JWoqgTFE',
    appId: '1:343403843881:ios:36ce6648131b2ba7592738',
    messagingSenderId: '343403843881',
    projectId: 'chatfriend-e2388',
    storageBucket: 'chatfriend-e2388.appspot.com',
    iosClientId: '343403843881-0oen6va09qhk152j78fv12lu2ra3hk5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFriend.RunnerTests',
  );
}
